apiVersion: v1 # Secret for store env variables
kind: Secret
metadata:
    name: api-secrets
type: Opaque
data:
    API_KEY: MmY1YWU5NmMtYjU1OC00YzdiLWE1OTAtYTUwMWFlMWMzZjZj
    JWT_TOKEN: ZmdoZXRoMjVoYg==