# Service for expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
  annotations:
    cloud.google.com/backend-config: '{"default": "restapi-backendconfig"}'
spec:
  #type: NodePort # expose the deployment as a load balancer
  selector:
    component: api
  sessionAffinity: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000

---

# Backend config for the service
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: restapi-backendconfig
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 4
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    port: 80
    requestPath: /DevOps