# Service for expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  type: LoadBalancer # expose the deployment as a load balancer
  selector:
    component: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000