apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: rest-api
          image: grc.io/devops-test-rest-api/api:{GITHUB_SHA} # pull image from docker registry
          ports:
            - containerPort: 4000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: API_KEY
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_TOKEN
          resources: # set resources limits
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
# Service for expose the deployment
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  type: LoadBalancer
  selector:
    component: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000