name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # Run on PRs to main branch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # node versions to test
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci # install dependencies
    - run: npm test # run tests (if any)