name: Node.js CI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # Run on PRs to main branch
#  push:
    # Turning off staging for now...
    # branches:
    #   - master
#    tags:
#
#      - v\d+\.\d+\.\d+

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  SHA: ${{ github.sha }}

jobs:
  test-stage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] # node versions to test
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci # install dependencies
    - run: npm test # run tests (if any)

  setup-build-publish-deploy:
    needs: test-stage # I'd depend on the test jobs to proceed with the deploy itself

    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
      
    steps:

      - name: Set ENV
        run: |-
          if [ ${GITHUB_REF##*/} = "main" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
          else 
            echo "ENV=production" >> $GITHUB_ENV
          fi
          
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
        #env:
        #  ENV: ${{ env.GITHUB_ENV}}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get GKE credentials
      - name: Get GKE credentials
        run: |-
          make get-credentials
        
      # Build the Docker image
      - name: Build
        run: |-
          make build

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          make push

      # Setting up kustomize
      - name: Set up Kustomize
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/   

      # Deploy to cluster
      - name: Deploy Image to Gke Cluster 
        run: |-
          make deploy
